// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqmZPcqo7Nqs4sADhQ3Ci0BT_jGqpKbUg',
    appId: '1:932497029962:web:987c514531f5226ed29fb3',
    messagingSenderId: '932497029962',
    projectId: 'roami-b0988',
    authDomain: 'roami-b0988.firebaseapp.com',
    storageBucket: 'roami-b0988.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqoCdNPJ2uqjVwUngrD8UAt68ZBg8dbp8',
    appId: '1:932497029962:android:87c6b5e3a57e1cf5d29fb3',
    messagingSenderId: '932497029962',
    projectId: 'roami-b0988',
    storageBucket: 'roami-b0988.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGiFfxSzgP38s3pAyl72xxfKeCaLpfwo8',
    appId: '1:932497029962:ios:80f7a4abab666626d29fb3',
    messagingSenderId: '932497029962',
    projectId: 'roami-b0988',
    storageBucket: 'roami-b0988.firebasestorage.app',
    iosBundleId: 'com.example.japanApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGiFfxSzgP38s3pAyl72xxfKeCaLpfwo8',
    appId: '1:932497029962:ios:80f7a4abab666626d29fb3',
    messagingSenderId: '932497029962',
    projectId: 'roami-b0988',
    storageBucket: 'roami-b0988.firebasestorage.app',
    iosBundleId: 'com.example.japanApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqmZPcqo7Nqs4sADhQ3Ci0BT_jGqpKbUg',
    appId: '1:932497029962:web:6a25d9f12fbf51cad29fb3',
    messagingSenderId: '932497029962',
    projectId: 'roami-b0988',
    authDomain: 'roami-b0988.firebaseapp.com',
    storageBucket: 'roami-b0988.firebasestorage.app',
  );
}
